### ISSUE TITLE
v. 1.001013 seems to be broken for large messages

### ISSUE THREAD

**Issue by als1** [TrackingSoft/Kafka#23]
The latest version of the package (1.001013) seems to be broken for large messages. I am using a very simple test case, which is basically the sample code in Kafka::Consumer using a 3 node kafka cluster at my site, and I am getting the following error in v. 1.001013

Error: (-1016) 'ResponseMessage' not received: response length=4

So after reading the first 4 bytes, it looks like the fetch() in this version doesn't block at all but times out pretty much immediately (or perhaps in 100ms, I can't tell). So perhaps this has something to do with the MaxWaitTime change in the latest version (from ms to seconds). I looked in the code briefly but didn't see anything obvious. The same code works fine in v. 1.001012, which blocks until the message is received (a few seconds). The size of the kafka data that causes this failure is about 630K bytes.

Let me know if I can provide more detail to track this down.

**Comment by asolovey** [comment]
Timeout handling was pretty much broken before v1.001013. Starting from this release, we try harder to use proper timeouts and large messages may hit those timeouts. Could you tell us what timeouts (if any) you use in Kafka::Connection and Kafka::Consumer constructors?

**Comment by als1** [comment]
I see. That explains why it didn't time out in the previous release (or any earlier release I used before).

I was not setting timeout values, so I was using defaults. I briefly experimented with setting Kafka::Connection timeout as well as Kafka::Consumer MaxWaitTime to a fairly high value but it didn't seem to make a difference. I will run some more tests tomorrow. Which on of these is the likely culprit? Do you have any idea what values I should try? Can I set the timeout to unlimited? In other words, in the script that runs into this issue, I want to wait till I get the entire message. Clearly, it got the first 4 bytes already, so I want to make sure I read all the rest instead of timing out if the network happens to be slow (though I am getting data within the same colo, so it shouldn't be too slow).

**Comment by asolovey** [comment]
> Clearly, it got the first 4 bytes already, 

This is the way how the protocol works. Logical read operations are made of two actual reads: first, read 4-byte header with actual response size; then, read the rest - we know its size now. But if the response is big enough, you can still hit the timeout.

> In other words, in the script that runs into this issue, I want to wait till I get the entire message

The problem is that Kafka protocol requires some timeout value for requests and responses. Due to a bug, we've been using big values there, but that was fixed. You can try using reasonable big values instead of defaults in Connection/Producer/Consumer constructors to wait longer for big messages, unless we miss something (like a new bug introduced in the last release).

I'd suggest setting `Kafka::Connection->new( ..., timeout => 20 )` for IO operations (default is 1.5), `Kafka::Consumer->new( ...., MaxWaitTime => 40 )` and see if this helps. If it does not, can you try enabling debug mode for Kafka module and collect its output?

**Comment by als1** [comment]
I think there is a problem with timeouts. I tried your suggested values, and there is pretty much no noticeable wait before I get the same error response (ie. presumably a timeout). I assume it should wait for at least 20 secs (Connection.timeout), or possibly 40 secs (Consumer.MaxWaitTime). Then I multiplied both of these values by 10 and then by 100, and there was still no difference in wait time.

How do I enable debug mode? Is it PERL_KAFKA_DEBUG=2?

**Comment by als1** [comment]
Here is the debug output with PERL_KAFKA_DEBUG=2. The timeout and MaxWaitTime values are the ones you suggested. Let me know if I can provide anything else to try to track this down. Thanks.

[kafka-debug.txt](https://github.com/TrackingSoft/Kafka/files/880508/kafka-debug.txt)

**Comment by asolovey** [comment]
Thanks for debug log. I'll take a look to see if there is a clue to your issue in there.

**Comment by asolovey** [comment]
I see the problem in debug log that you've provided. The first read from the network succeeded and returned valid response size (20971565 bytes). But for some reason, there were no subsequent reads from the network and only those first 4 bytes were returned instead of 4+20971565.
We do not see such situations in our usage of Kafka module, but we do not have big messages so I need to figure out what's going on there. Unfortunately, I won't be able to work on this for the next 7-10 days or so.
